### PR TITLE
applying script loader to .src scripts

### PR DESCRIPTION
**Pull request by Jimexist**
need to apply the loader to script loaded via `.src` way

@imyelo please take a look and help republish.

### CODE REVIEW

**Comment by Jimexist** [comment]
@imyelo updated with tests.

seem that the `basic` test should've been updated as well.

**Comment by Jimexist** [comment]
but for now i'm just updating the separation test cases, for both `.es`. and `.ts` files. the `loaders` property should've been configured for `mina-loader`

**Comment by imyelo** [comment]
@Jimexist The latest commit I  just pushed might be a better solution to this topic, please make sure that it also meets your needs.

**Comment by Jimexist** [comment]
@imyelo i think as long as the test cases are passing then we are good to go 👍

**Pull request merged**
