### PR TITLE
support WXML component

### PR DESCRIPTION
**Pull request by huanghui1**
support WXML component in usingComponents

### CODE REVIEW

**Comment by imyelo** [comment]
Sorry to respond so late. 

I don't think this change is necessary. 
The pattern used in the test case is [Custom component (自定义组件)](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/), not [Including wxml file (引用 wxml 文件)](https://developers.weixin.qq.com/miniprogram/dev/framework/view/wxml/import.html). 

To satisfy the test case in this pull request, just simply change the extname of the component file to ``.mina``, or any other name that is resolved using ``mina-loader`` in the webpack configuration. We don't do any special handling of extnames in a loader. 

In the case of wxml files, you need to use the ``include`` or ``import`` tags in the template block of the mina file. For a more detailed usages, you can view [this test case file](https://github.com/tinajs/mina-webpack/blob/76c4ba65ad9015ecf6ce741262c6e498a6bd58e8/packages/mina-loader/test/template.js) .

Please let me know if I’m missing anything. 😉

**Comment by huanghui1** [comment]
+1。

I just wanna add [minUI](https://meili.github.io/min/index.html) to my project, but this change really against pattern of Single File Component.

`import` need <template> contained. `include` do not support props. Both of them do not satisfy the [minUI Component case](https://meili.github.io/min/docs/min-cli/third-project/using/index.html). With my changes, it works.

However, I think you are right.

**Comment by imyelo** [comment]
Oh, I see what you're trying to do now. 

It is difficult to mix the two patterns (separation of file types and single file components) in the same project. To use a custom-component with separation of file types, we may first need a tool to merge and convert them into a single file component. I imagine it might be ``merge-to-mina-cli`` ? 🤔

Another way of thinking about using components provided by MinUI is to write a loader to convert files in [Min single file mode format](https://meili.github.io/min/docs/features/single-file-mode.html) to ``mina``. I think it would be a more user-friendly solution.

**Comment by imyelo** [comment]
As a result of the following changes, it should be easier to support this feature now:

- https://github.com/tinajs/mina-webpack/pull/40
- https://github.com/tinajs/mina-webpack/commit/966ff813480fc5d2588f0f6e1e3eb5bff3f20aef

**Pull request closed without merging**
